version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    volumes:
      - /Users/dev/realTimeNotification:/rails
    command: /rails/bin/docker-entrypoint
    stdin_open: true
    tty: true
    user: "rails"
    entrypoint: ["/bin/bash", "-c"]
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
